steam:
  dirs:
    hdd: C:\home\games\steam\steamapps\common
    ssd: C:\home\games\ssd\steam
  ignore:
    - steamapps
uplay:
  dirs:
    hdd: C:\home\games\uplay
    ssd: C:\home\games\ssd\uplay
bethesda:
  dirs:
    hdd: C:\home\games\bethesda
    ssd: C:\home\games\ssd\bethesda
origin:
  dirs:
    hdd: C:\home\games\origin
    ssd: C:\home\games\ssd\origin
  ignore:
    - installers
gog:
  dirs:
    hdd: C:\home\games\gog
    ssd: C:\home\games\ssd\gog
battle.net:
  dirs:
    hdd: C:\home\games\battle.net
    ssd: C:\home\games\ssd\battle.net
epic:
  dirs:
    hdd: C:\home\games\bucket\epic
    ssd: C:\home\games\ssd\epic
twitch:
  dirs:
    hdd: C:\home\games\twitch
    ssd: C:\home\games\ssd\twitch